# Generated by Django 3.0.4 on 2020-04-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Страна', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_opening', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название тура', max_length=200)),
                ('description', models.TextField(help_text='Краткое описание тура', max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип тура', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TourInstance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_of_departure', models.DateField(blank=True)),
                ('date_of_arrival', models.DateField(blank=True)),
                ('number_of_seats', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Tour')),
            ],
            options={
                'ordering': ['date_of_departure'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(help_text='Тип тура', on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.Type'),
        ),
        migrations.CreateModel(
            name='ProfileTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('tour', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.TourInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('tickets', models.ManyToManyField(blank=True, to='firstapp.ProfileTickets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reply_capt', models.CharField(blank=True, max_length=500, verbose_name='Заголовок ответа на e-mail')),
                ('email_reply_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа на e-mail')),
                ('email_reply_date', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('email_reply_adress', models.ManyToManyField(blank=True, null=True, to='firstapp.Profile')),
            ],
        ),
    ]
